# Generated by Django 5.1.4 on 2025-02-04 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0002_alter_volleyball_image_alter_volleyball_price_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='security_question_answer',
            new_name='security_answer',
        ),
    ]
