# Generated by Django 5.1.4 on 2025-02-04 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0003_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='security_answer',
            new_name='security_question_answer',
        ),
    ]
