# Generated by Django 5.1.4 on 2025-02-04 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volleyball', '0005_alter_customuser_security_question_answer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='security_question_answer',
            new_name='security_answer',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='volleyball_customuser',
        ),
    ]
