"""
Django settings for ccse1 project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

try:
    from django.core.servers.basehttp import WSGIRequestHandler

    # 1) blank out the version string used by BaseHTTPRequestHandler
    WSGIRequestHandler.server_version = "secure"
    WSGIRequestHandler.sys_version = ""

    # 2) drop any explicit "Server:" header that send_header may write
    _orig_send_header = WSGIRequestHandler.send_header

    def _send_header_no_server(self, keyword, value, *args, **kwargs):
        if keyword.lower() == "server":
            return                          # skip it
        return _orig_send_header(self, keyword, value, *args, **kwargs)

    WSGIRequestHandler.send_header = _send_header_no_server
except ImportError:
    pass

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")    # load variables before we reference them


AUTH_USER_MODEL = 'volleyball.CustomUser'

CSRF_COOKIE_SECURE = True           # cookie only over HTTPS

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

SECRET_KEY = os.getenv("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

env_hosts = os.getenv('ALLOWED_HOSTS', '').split(',')
render_host = os.getenv('RENDER_EXTERNAL_HOSTNAME')

ALLOWED_HOSTS = [
    *filter(None, env_hosts),  
    render_host,                
    'localhost',
    '127.0.0.1',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'volleyball.apps.VolleyballConfig',
    'csp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    "csp.middleware.CSPMiddleware",
    "ccse1.security_headers.PermissionsPolicyMiddleware",
    "ccse1.security_headers.StripServerHeaderMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# New django-csp 4.0+ settings
CONTENT_SECURITY_POLICY = {
    "DIRECTIVES": {
        "default-src": ("'self'",),
        "style-src":   ("'self'", "fonts.googleapis.com"),
        "font-src":    ("'self'", "fonts.gstatic.com"),
        "script-src":  ("'self'",),
        "object-src":  ("'none'",),
        "base-uri":    ("'self'",),
        "form-action": ("'self'",),
        "frame-ancestors": ("'none'",),
    },
}

ROOT_URLCONF = 'ccse1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ccse1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
